### PR TITLE
Fix bug when there no entries for a response category

### LINKED ISSUE #116: Choosing a topic that doesn't have entries will result in an error
image

Click on crime

Because of this `action.js`

```
function shouldFetchResponses(state, answerId) {
  var _state$responses = state.responses;
  var collections = _state$responses.collections;
  var isFetching = _state$responses.isFetching;

  return !collections[answerId].length && !isFetching[answerId];
}
```

There is no collections[answerId] entry

### PR DESCRIPTION
**Pull request by pbeshai**
- Fixes the should fetch function to handle it without erroring
- Disables clicking the bar
- Fixes error in selecting topic/emoji that did not properly select the right topic/emoji.

Resolves #116

### CODE REVIEW

File: src/components/TopicBarChart.js [hunk 1]
```diff
@@ -47,15 +47,20 @@ class TopicBarChart extends PureComponent {
...
+              disabled
             });
+
             return (
               <button
                 aria-pressed={isSelected}
                 onClick={() => onSelect(topic.id)}
                 key={topic.value}
                 className={classes}
+                disabled={disabled}
```
Comment (kadamwhite) [inline src/components/TopicBarChart.js:63]: Oh, this works? I thought I had to do `disabled ? true : null` to get it not to render the attr earlier

Comment (kadamwhite) [reply src/components/TopicBarChart.js:63]: _wait that was D3_, disregard :)

**Review by iros — APPROVED** [review]

File: src/containers/FilterByTopicVis.js [hunk 2]
```diff
@@ -65,22 +65,25 @@ class FilterByTopicVis extends PureComponent {
...
 
-  showNextLetter() {
+  showNextLetter(topicId, emojiId) {
     const { dispatch, selectedTopic, selectedTopicEmoji } = this.props;
+    topicId = topicId || (selectedTopic && selectedTopic.id);
+
     if (selectedTopicEmoji) {
-      dispatch(showNextLetter(selectedTopic.id, selectedTopicEmoji.id));
+      emojiId = emojiId || selectedTopicEmoji.id;
+      dispatch(showNextLetter(topicId, emojiId));
```
Comment (kadamwhite) [inline src/containers/FilterByTopicVis.js:84]: Nice catch on this
